
# This script creates the test files for the project
DATADIR="./data"
TESTSDIR=$DATADIR"/TestFiles"
ENCODEDDIR=$DATADIR"/EncodedFiles"
ThreadsDIR=$ENCODEDDIR"/Threads"
AsyncDIR=$ENCODEDDIR"/Async"
ThreadPooDIR=$ENCODEDDIR"/ThreadPool"
FastFlowDIR=$ENCODEDDIR"/FastFlow"
SequentialDIR=$ENCODEDDIR"/Sequential"

# If not already present, create the data directory
if [ ! -d "$DATADIR" ]; then
    mkdir "$DATADIR"
fi

# If not already present, create the tests directory
if [ ! -d "$TESTSDIR" ]; then
    mkdir "$TESTSDIR"
fi

# If not already present, create the encoded directory
if [ ! -d "$ENCODEDDIR" ]; then
    mkdir "$ENCODEDDIR"
fi

# If not already present, create the threads directory
if [ ! -d "$ThreadsDIR" ]; then
    mkdir "$ThreadsDIR"
fi

# If not already present, create the async directory
if [ ! -d "$AsyncDIR" ]; then
    mkdir "$AsyncDIR"
fi

# If not already present, create the threadpool directory
if [ ! -d "$ThreadPooDIR" ]; then
    mkdir "$ThreadPooDIR"
fi

# If not already present, create the fastflow directory
if [ ! -d "$FastFlowDIR" ]; then
    mkdir "$FastFlowDIR"
fi

# If not already present, create the sequential directory
if [ ! -d "$SequentialDIR" ]; then
    mkdir "$SequentialDIR"
fi

LoremIpsum="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam scelerisque neque tincidunt volutpat. Nullam pretium efficitur risus eget varius. Donec mattis consectetur iaculis. Duis metus sem, semper ac nisi in, maximus ultrices diam. Maecenas viverra mauris eget ipsum accumsan consequat ac eget metus. Integer odio neque, accumsan vitae nisi eu, dignissim ultrices odio. Quisque vulputate fringilla nisl nec elementum. Proin ullamcorper ante sit amet dui condimentum aliquet. Vivamus eu congue justo. Pellentesque dictum a ex vel mollis. Nulla sit amet tellus sit amet leo gravida tempus. Vivamus sollicitudin nisl at risus viverra, vel tincidunt velit euismod.
Vestibulum posuere dolor quis eros imperdiet commodo. Vivamus ac est aliquet, finibus urna nec, sodales neque. Proin hendrerit tortor ullamcorper, bibendum purus sit amet, pretium quam. Donec ultrices nibh at leo pretium, non eleifend nibh sagittis. Vestibulum tincidunt tempus hendrerit. Etiam nec mauris a massa gravida vestibulum id sollicitudin tellus. Nam tempus pharetra vestibulum. Nam purus sapien, aliquet sed purus at, fermentum varius velit. Sed placerat est ac lectus pharetra, vitae porta enim scelerisque. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Quisque elementum placerat orci, a convallis quam commodo sit amet. Pellentesque hendrerit id justo non fringilla. Quisque ac pretium tellus. Fusce luctus at erat id hendrerit. Suspendisse a augue a enim posuere volutpat id eget metus. Phasellus vehicula augue sed eros eleifend posuere et nec sem. Quisque vitae pellentesque turpis. Integer non accumsan lorem. Morbi at quam a dolor tincidunt dapibus. Aenean sollicitudin in ante id hendrerit. Donec condimentum, ligula at varius lacinia, ante erat tempus mauris, ut posuere ex diam vel nulla. Donec dictum aliquet lectus. Aliquam sit amet magna sed justo vestibulum convallis. In vel odio vel ipsum viverra viverra.
Mauris malesuada libero egestas enim efficitur dictum. Nunc ultricies tristique sem, non iaculis justo convallis eu. Nullam ante nisi, suscipit sit amet tristique ac, commodo non nisi. Praesent varius libero eget posuere finibus. Etiam pretium vestibulum justo a convallis. Nulla suscipit arcu ut eros iaculis sollicitudin. Maecenas eget nulla sed tortor eleifend venenatis non sed mi. Curabitur porttitor et enim sed tempor. Mauris nulla massa, porta a aliquet eget, commodo in nunc. Duis finibus ex non tempor pellentesque. Donec tincidunt sapien id mi ultricies, mattis vulputate ipsum accumsan. Donec quis lobortis erat.
Vivamus maximus blandit est, eu malesuada sem. Vivamus hendrerit varius ligula commodo tempus. Nulla euismod, dolor sit amet rhoncus posuere, est sapien tincidunt nulla, eget bibendum velit neque ac lacus. Sed finibus tortor a condimentum ornare. Vivamus ut tincidunt velit, consequat convallis magna. Aenean id nulla ut nisl tristique placerat. Fusce non nisi lobortis mi blandit vulputate sit amet ut lacus. Mauris metus nisl, facilisis et sollicitudin at, blandit interdum odio. Curabitur interdum sapien sit amet justo mattis, sit amet ultrices est interdum. Aenean non odio vitae massa consectetur placerat. Etiam laoreet varius justo vel consequat. Sed venenatis urna vel fringilla tincidunt. Aenean vulputate, metus quis convallis congue, mauris lectus imperdiet quam, in laoreet augue urna lacinia magna. Duis malesuada sapien quis dui consectetur, non dignissim velit luctus. Etiam pharetra neque a felis elementum, non bibendum lorem iaculis. Suspendisse laoreet urna sem, sit amet venenatis lectus consequat sollicitudin.
Phasellus tincidunt euismod diam sed elementum. Donec sit amet ligula consequat, blandit magna in, maximus ligula. Maecenas sit amet tincidunt tortor, ut porttitor est. Curabitur ante erat, tempus mollis efficitur vitae, varius ut eros. Maecenas purus odio, gravida ut euismod quis, tempor in nulla. Pellentesque sed justo in tortor tincidunt consectetur sit amet ut enim. Nam euismod leo ac iaculis rutrum. Sed pharetra nunc condimentum arcu consectetur, eu pulvinar nulla posuere. Vivamus vitae neque eget metus gravida ornare. Nunc sed cursus purus. Nunc risus mi, tincidunt vel rutrum a, viverra id tortor. Aliquam sit amet enim turpis. Ut neque velit, tincidunt id varius nec, ullamcorper luctus leo.
Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum vel sodales felis, eget ultricies neque. Proin ut commodo felis, nec aliquam mauris. Integer at est tristique, malesuada turpis a, elementum ante. Suspendisse aliquet elit in ante tristique porttitor. Phasellus ultricies ipsum faucibus, laoreet dolor rhoncus, elementum tortor. Praesent bibendum magna nisi, vitae consequat purus tincidunt eu. Cras venenatis vehicula nibh quis efficitur. Maecenas aliquet, tellus sed pulvinar accumsan, velit arcu pulvinar lacus, id faucibus nisl ipsum quis metus. Aliquam vestibulum, lacus sit amet luctus sollicitudin, nisl lacus elementum arcu, sit amet aliquam mauris libero condimentum nulla. Quisque ultricies accumsan fermentum. Fusce aliquam nunc at urna varius tempor. In molestie sollicitudin sem, id pulvinar orci gravida id. Cras suscipit ornare volutpat.
Nullam luctus molestie lacus posuere eleifend. Cras consectetur tincidunt viverra. Ut nec elit nec est facilisis mattis. Integer tristique consequat gravida. Nulla sit amet tincidunt odio. Proin in massa orci. Suspendisse mattis non nunc vel facilisis.
Pellentesque pretium feugiat placerat. Sed non mauris sed ligula semper vulputate sit amet vehicula nibh. Maecenas accumsan lorem vitae mi pharetra congue. Nulla purus enim, lacinia sed convallis nec, iaculis eu arcu. Vivamus nisl mauris, sollicitudin at magna a, sagittis suscipit eros. In hac habitasse platea dictumst. Aliquam gravida orci augue, quis venenatis risus volutpat vitae. Duis vel augue dignissim, viverra ante at, rutrum mi. Nullam venenatis posuere nisi at malesuada.
Nunc eu quam posuere nisi auctor lobortis. Vestibulum vestibulum est vel purus faucibus, quis tristique velit sagittis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In sodales dui eu iaculis placerat. Nulla semper sem quis nibh dapibus, consectetur ullamcorper urna posuere. Aenean faucibus tincidunt ligula, et consectetur risus rutrum in. Nunc vel scelerisque velit, laoreet posuere orci. Sed tempus auctor quam a pulvinar. Donec felis nibh, auctor ut mattis et, bibendum eget eros. Curabitur eleifend quam vel ex consequat bibendum. Pellentesque et libero sit amet erat dignissim posuere.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam scelerisque neque tincidunt volutpat. Nullam pretium efficitur risus eget varius. Donec mattis consectetur iaculis. Duis metus sem, semper ac nisi in, maximus ultrices diam. Maecenas viverra mauris eget ipsum accumsan consequat ac eget metus. Integer odio neque, accumsan vitae nisi eu, dignissim ultrices odio. Quisque vulputate fringilla nisl nec elementum. Proin ullamcorper ante sit amet dui condimentum aliquet. Vivamus eu congue justo. Pellentesque dictum a ex vel mollis. Nulla sit amet tellus sit amet leo gravida tempus. Vivamus sollicitudin nisl at risus viverra, vel tincidunt velit euismod.
Vestibulum posuere dolor quis eros imperdiet commodo. Vivamus ac est aliquet, finibus urna nec, sodales neque. Proin hendrerit tortor ullamcorper, bibendum purus sit amet, pretium quam. Donec ultrices nibh at leo pretium, non eleifend nibh sagittis. Vestibulum tincidunt tempus hendrerit. Etiam nec mauris a massa gravida vestibulum id sollicitudin tellus. Nam tempus pharetra vestibulum. Nam purus sapien, aliquet sed purus at, fermentum varius velit. Sed placerat est ac lectus pharetra, vitae porta enim scelerisque. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Quisque elementum placerat orci, a convallis quam commodo sit amet. Pellentesque hendrerit id justo non fringilla. Quisque ac pretium tellus. Fusce luctus at erat id hendrerit. Suspendisse a augue a enim posuere volutpat id eget metus. Phasellus vehicula augue sed eros eleifend posuere et nec sem. Quisque vitae pellentesque turpis. Integer non accumsan lorem. Morbi at quam a dolor tincidunt dapibus. Aenean sollicitudin in ante id hendrerit. Donec condimentum, ligula at varius lacinia, ante erat tempus mauris, ut posuere ex diam vel nulla. Donec dictum aliquet lectus. Aliquam sit amet magna sed justo vestibulum convallis. In vel odio vel ipsum viverra viverra.
Mauris malesuada libero egestas enim efficitur dictum. Nunc ultricies tristique sem, non iaculis justo convallis eu. Nullam ante nisi, suscipit sit amet tristique ac, commodo non nisi. Praesent varius libero eget posuere finibus. Etiam pretium vestibulum justo a convallis. Nulla suscipit arcu ut eros iaculis sollicitudin. Maecenas eget nulla sed tortor eleifend venenatis non sed mi. Curabitur porttitor et enim sed tempor. Mauris nulla massa, porta a aliquet eget, commodo in nunc. Duis finibus ex non tempor pellentesque. Donec tincidunt sapien id mi ultricies, mattis vulputate ipsum accumsan. Donec quis lobortis erat.
Vivamus maximus blandit est, eu malesuada sem. Vivamus hendrerit varius ligula commodo tempus. Nulla euismod, dolor sit amet rhoncus posuere, est sapien tincidunt nulla, eget bibendum velit neque ac lacus. Sed finibus tortor a condimentum ornare. Vivamus ut tincidunt velit, consequat convallis magna. Aenean id nulla ut nisl tristique placerat. Fusce non nisi lobortis mi blandit vulputate sit amet ut lacus. Mauris metus nisl, facilisis et sollicitudin at, blandit interdum odio. Curabitur interdum sapien sit amet justo mattis, sit amet ultrices est interdum. Aenean non odio vitae massa consectetur placerat. Etiam laoreet varius justo vel consequat. Sed venenatis urna vel fringilla tincidunt. Aenean vulputate, metus quis convallis congue, mauris lectus imperdiet quam, in laoreet augue urna lacinia magna. Duis malesuada sapien quis dui consectetur, non dignissim velit luctus. Etiam pharetra neque a felis elementum, non bibendum lorem iaculis. Suspendisse laoreet urna sem, sit amet venenatis lectus consequat sollicitudin.
Phasellus tincidunt euismod diam sed elementum. Donec sit amet ligula consequat, blandit magna in, maximus ligula. Maecenas sit amet tincidunt tortor, ut porttitor est. Curabitur ante erat, tempus mollis efficitur vitae, varius ut eros. Maecenas purus odio, gravida ut euismod quis, tempor in nulla. Pellentesque sed justo in tortor tincidunt consectetur sit amet ut enim. Nam euismod leo ac iaculis rutrum. Sed pharetra nunc condimentum arcu consectetur, eu pulvinar nulla posuere. Vivamus vitae neque eget metus gravida ornare. Nunc sed cursus purus. Nunc risus mi, tincidunt vel rutrum a, viverra id tortor. Aliquam sit amet enim turpis. Ut neque velit, tincidunt id varius nec, ullamcorper luctus leo.
Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum vel sodales felis, eget ultricies neque. Proin ut commodo felis, nec aliquam mauris. Integer at est tristique, malesuada turpis a, elementum ante. Suspendisse aliquet elit in ante tristique porttitor. Phasellus ultricies ipsum faucibus, laoreet dolor rhoncus, elementum tortor. Praesent bibendum magna nisi, vitae consequat purus tincidunt eu. Cras venenatis vehicula nibh quis efficitur. Maecenas aliquet, tellus sed pulvinar accumsan, velit arcu pulvinar lacus, id faucibus nisl ipsum quis metus. Aliquam vestibulum, lacus sit amet luctus sollicitudin, nisl lacus elementum arcu, sit amet aliquam mauris libero condimentum nulla. Quisque ultricies accumsan fermentum. Fusce aliquam nunc at urna varius tempor. In molestie sollicitudin sem, id pulvinar orci gravida id. Cras suscipit ornare volutpat.
Nullam luctus molestie lacus posuere eleifend. Cras consectetur tincidunt viverra. Ut nec elit nec est facilisis mattis. Integer tristique consequat gravida. Nulla sit amet tincidunt odio. Proin in massa orci. Suspendisse mattis non nunc vel facilisis.
Pellentesque pretium feugiat placerat. Sed non mauris sed ligula semper vulputate sit amet vehicula nibh. Maecenas accumsan lorem vitae mi pharetra congue. Nulla purus enim, lacinia sed convallis nec, iaculis eu arcu. Vivamus nisl mauris, sollicitudin at magna a, sagittis suscipit eros. In hac habitasse platea dictumst. Aliquam gravida orci augue, quis venenatis risus volutpat vitae. Duis vel augue dignissim, viverra ante at, rutrum mi. Nullam venenatis posuere nisi at malesuada.
Nunc eu quam posuere nisi auctor lobortis. Vestibulum vestibulum est vel purus faucibus, quis tristique velit sagittis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In sodales dui eu iaculis placerat. Nulla semper sem quis nibh dapibus, consectetur ullamcorper urna posuere. Aenean faucibus tincidunt ligula, et consectetur risus rutrum in. Nunc vel scelerisque velit, laoreet posuere orci. Sed tempus auctor quam a pulvinar. Donec felis nibh, auctor ut mattis et, bibendum eget eros. Curabitur eleifend quam vel ex consequat bibendum. Pellentesque et libero sit amet erat dignissim posuere.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam scelerisque neque tincidunt volutpat. Nullam pretium efficitur risus eget varius. Donec mattis consectetur iaculis. Duis metus sem, semper ac nisi in, maximus ultrices diam. Maecenas viverra mauris eget ipsum accumsan consequat ac eget metus. Integer odio neque, accumsan vitae nisi eu, dignissim ultrices odio. Quisque vulputate fringilla nisl nec elementum. Proin ullamcorper ante sit amet dui condimentum aliquet. Vivamus eu congue justo. Pellentesque dictum a ex vel mollis. Nulla sit amet tellus sit amet leo gravida tempus. Vivamus sollicitudin nisl at risus viverra, vel tincidunt velit euismod.
Vestibulum posuere dolor quis eros imperdiet commodo. Vivamus ac est aliquet, finibus urna nec, sodales neque. Proin hendrerit tortor ullamcorper, bibendum purus sit amet, pretium quam. Donec ultrices nibh at leo pretium, non eleifend nibh sagittis. Vestibulum tincidunt tempus hendrerit. Etiam nec mauris a massa gravida vestibulum id sollicitudin tellus. Nam tempus pharetra vestibulum. Nam purus sapien, aliquet sed purus at, fermentum varius velit. Sed placerat est ac lectus pharetra, vitae porta enim scelerisque. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Quisque elementum placerat orci, a convallis quam commodo sit amet. Pellentesque hendrerit id justo non fringilla. Quisque ac pretium tellus. Fusce luctus at erat id hendrerit. Suspendisse a augue a enim posuere volutpat id eget metus. Phasellus vehicula augue sed eros eleifend posuere et nec sem. Quisque vitae pellentesque turpis. Integer non accumsan lorem. Morbi at quam a dolor tincidunt dapibus. Aenean sollicitudin in ante id hendrerit. Donec condimentum, ligula at varius lacinia, ante erat tempus mauris, ut posuere ex diam vel nulla. Donec dictum aliquet lectus. Aliquam sit amet magna sed justo vestibulum convallis. In vel odio vel ipsum viverra viverra.
Mauris malesuada libero egestas enim efficitur dictum. Nunc ultricies tristique sem, non iaculis justo convallis eu. Nullam ante nisi, suscipit sit amet tristique ac, commodo non nisi. Praesent varius libero eget posuere finibus. Etiam pretium vestibulum justo a convallis. Nulla suscipit arcu ut eros iaculis sollicitudin. Maecenas eget nulla sed tortor eleifend venenatis non sed mi. Curabitur porttitor et enim sed tempor. Mauris nulla massa, porta a aliquet eget, commodo in nunc. Duis finibus ex non tempor pellentesque. Donec tincidunt sapien id mi ultricies, mattis vulputate ipsum accumsan. Donec quis lobortis erat.
Vivamus maximus blandit est, eu malesuada sem. Vivamus hendrerit varius ligula commodo tempus. Nulla euismod, dolor sit amet rhoncus posuere, est sapien tincidunt nulla, eget bibendum velit neque ac lacus. Sed finibus tortor a condimentum ornare. Vivamus ut tincidunt velit, consequat convallis magna. Aenean id nulla ut nisl tristique placerat. Fusce non nisi lobortis mi blandit vulputate sit amet ut lacus. Mauris metus nisl, facilisis et sollicitudin at, blandit interdum odio. Curabitur interdum sapien sit amet justo mattis, sit amet ultrices est interdum. Aenean non odio vitae massa consectetur placerat. Etiam laoreet varius justo vel consequat. Sed venenatis urna vel fringilla tincidunt. Aenean vulputate, metus quis convallis congue, mauris lectus imperdiet quam, in laoreet augue urna lacinia magna. Duis malesuada sapien quis dui consectetur, non dignissim velit luctus. Etiam pharetra neque a felis elementum, non bibendum lorem iaculis. Suspendisse laoreet urna sem, sit amet venenatis lectus consequat sollicitudin.
Phasellus tincidunt euismod diam sed elementum. Donec sit amet ligula consequat, blandit magna in, maximus ligula. Maecenas sit amet tincidunt tortor, ut porttitor est. Curabitur ante erat, tempus mollis efficitur vitae, varius ut eros. Maecenas purus odio, gravida ut euismod quis, tempor in nulla. Pellentesque sed justo in tortor tincidunt consectetur sit amet ut enim. Nam euismod leo ac iaculis rutrum. Sed pharetra nunc condimentum arcu consectetur, eu pulvinar nulla posuere. Vivamus vitae neque eget metus gravida ornare. Nunc sed cursus purus. Nunc risus mi, tincidunt vel rutrum a, viverra id tortor. Aliquam sit amet enim turpis. Ut neque velit, tincidunt id varius nec, ullamcorper luctus leo.
Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum vel sodales felis, eget ultricies neque. Proin ut commodo felis, nec aliquam mauris. Integer at est tristique, malesuada turpis a, elementum ante. Suspendisse aliquet elit in ante tristique porttitor. Phasellus ultricies ipsum faucibus, laoreet dolor rhoncus, elementum tortor. Praesent bibendum magna nisi, vitae consequat purus tincidunt eu. Cras venenatis vehicula nibh quis efficitur. Maecenas aliquet, tellus sed pulvinar accumsan, velit arcu pulvinar lacus, id faucibus nisl ipsum quis metus. Aliquam vestibulum, lacus sit amet luctus sollicitudin, nisl lacus elementum arcu, sit amet aliquam mauris libero condimentum nulla. Quisque ultricies accumsan fermentum. Fusce aliquam nunc at urna varius tempor. In molestie sollicitudin sem, id pulvinar orci gravida id. Cras suscipit ornare volutpat.
Nullam luctus molestie lacus posuere eleifend. Cras consectetur tincidunt viverra. Ut nec elit nec est facilisis mattis. Integer tristique consequat gravida. Nulla sit amet tincidunt odio. Proin in massa orci. Suspendisse mattis non nunc vel facilisis.
Pellentesque pretium feugiat placerat. Sed non mauris sed ligula semper vulputate sit amet vehicula nibh. Maecenas accumsan lorem vitae mi pharetra congue. Nulla purus enim, lacinia sed convallis nec, iaculis eu arcu. Vivamus nisl mauris, sollicitudin at magna a, sagittis suscipit eros. In hac habitasse platea dictumst. Aliquam gravida orci augue, quis venenatis risus volutpat vitae. Duis vel augue dignissim, viverra ante at, rutrum mi. Nullam venenatis posuere nisi at malesuada.
Nunc eu quam posuere nisi auctor lobortis. Vestibulum vestibulum est vel purus faucibus, quis tristique velit sagittis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In sodales dui eu iaculis placerat. Nulla semper sem quis nibh dapibus, consectetur ullamcorper urna posuere. Aenean faucibus tincidunt ligula, et consectetur risus rutrum in. Nunc vel scelerisque velit, laoreet posuere orci. Sed tempus auctor quam a pulvinar. Donec felis nibh, auctor ut mattis et, bibendum eget eros. Curabitur eleifend quam vel ex consequat bibendum. Pellentesque et libero sit amet erat dignissim posuere.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam scelerisque neque tincidunt volutpat. Nullam pretium efficitur risus eget varius. Donec mattis consectetur iaculis. Duis metus sem, semper ac nisi in, maximus ultrices diam. Maecenas viverra mauris eget ipsum accumsan consequat ac eget metus. Integer odio neque, accumsan vitae nisi eu, dignissim ultrices odio. Quisque vulputate fringilla nisl nec elementum. Proin ullamcorper ante sit amet dui condimentum aliquet. Vivamus eu congue justo. Pellentesque dictum a ex vel mollis. Nulla sit amet tellus sit amet leo gravida tempus. Vivamus sollicitudin nisl at risus viverra, vel tincidunt velit euismod.
Vestibulum posuere dolor quis eros imperdiet commodo. Vivamus ac est aliquet, finibus urna nec, sodales neque. Proin hendrerit tortor ullamcorper, bibendum purus sit amet, pretium quam. Donec ultrices nibh at leo pretium, non eleifend nibh sagittis. Vestibulum tincidunt tempus hendrerit. Etiam nec mauris a massa gravida vestibulum id sollicitudin tellus. Nam tempus pharetra vestibulum. Nam purus sapien, aliquet sed purus at, fermentum varius velit. Sed placerat est ac lectus pharetra, vitae porta enim scelerisque. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Quisque elementum placerat orci, a convallis quam commodo sit amet. Pellentesque hendrerit id justo non fringilla. Quisque ac pretium tellus. Fusce luctus at erat id hendrerit. Suspendisse a augue a enim posuere volutpat id eget metus. Phasellus vehicula augue sed eros eleifend posuere et nec sem. Quisque vitae pellentesque turpis. Integer non accumsan lorem. Morbi at quam a dolor tincidunt dapibus. Aenean sollicitudin in ante id hendrerit. Donec condimentum, ligula at varius lacinia, ante erat tempus mauris, ut posuere ex diam vel nulla. Donec dictum aliquet lectus. Aliquam sit amet magna sed justo vestibulum convallis. In vel odio vel ipsum viverra viverra.
Mauris malesuada libero egestas enim efficitur dictum. Nunc ultricies tristique sem, non iaculis justo convallis eu. Nullam ante nisi, suscipit sit amet tristique ac, commodo non nisi. Praesent varius libero eget posuere finibus. Etiam pretium vestibulum justo a convallis. Nulla suscipit arcu ut eros iaculis sollicitudin. Maecenas eget nulla sed tortor eleifend venenatis non sed mi. Curabitur porttitor et enim sed tempor. Mauris nulla massa, porta a aliquet eget, commodo in nunc. Duis finibus ex non tempor pellentesque. Donec tincidunt sapien id mi ultricies, mattis vulputate ipsum accumsan. Donec quis lobortis erat.
Vivamus maximus blandit est, eu malesuada sem. Vivamus hendrerit varius ligula commodo tempus. Nulla euismod, dolor sit amet rhoncus posuere, est sapien tincidunt nulla, eget bibendum velit neque ac lacus. Sed finibus tortor a condimentum ornare. Vivamus ut tincidunt velit, consequat convallis magna. Aenean id nulla ut nisl tristique placerat. Fusce non nisi lobortis mi blandit vulputate sit amet ut lacus. Mauris metus nisl, facilisis et sollicitudin at, blandit interdum odio. Curabitur interdum sapien sit amet justo mattis, sit amet ultrices est interdum. Aenean non odio vitae massa consectetur placerat. Etiam laoreet varius justo vel consequat. Sed venenatis urna vel fringilla tincidunt. Aenean vulputate, metus quis convallis congue, mauris lectus imperdiet quam, in laoreet augue urna lacinia magna. Duis malesuada sapien quis dui consectetur, non dignissim velit luctus. Etiam pharetra neque a felis elementum, non bibendum lorem iaculis. Suspendisse laoreet urna sem, sit amet venenatis lectus consequat sollicitudin.
Phasellus tincidunt euismod diam sed elementum. Donec sit amet ligula consequat, blandit magna in, maximus ligula. Maecenas sit amet tincidunt tortor, ut porttitor est. Curabitur ante erat, tempus mollis efficitur vitae, varius ut eros. Maecenas purus odio, gravida ut euismod quis, tempor in nulla. Pellentesque sed justo in tortor tincidunt consectetur sit amet ut enim. Nam euismod leo ac iaculis rutrum. Sed pharetra nunc condimentum arcu consectetur, eu pulvinar nulla posuere. Vivamus vitae neque eget metus gravida ornare. Nunc sed cursus purus. Nunc risus mi, tincidunt vel rutrum a, viverra id tortor. Aliquam sit amet enim turpis. Ut neque velit, tincidunt id varius nec, ullamcorper luctus leo.
Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum vel sodales felis, eget ultricies neque. Proin ut commodo felis, nec aliquam mauris. Integer at est tristique, malesuada turpis a, elementum ante. Suspendisse aliquet elit in ante tristique porttitor. Phasellus ultricies ipsum faucibus, laoreet dolor rhoncus, elementum tortor. Praesent bibendum magna nisi, vitae consequat purus tincidunt eu. Cras venenatis vehicula nibh quis efficitur. Maecenas aliquet, tellus sed pulvinar accumsan, velit arcu pulvinar lacus, id faucibus nisl ipsum quis metus. Aliquam vestibulum, lacus sit amet luctus sollicitudin, nisl lacus elementum arcu, sit amet aliquam mauris libero condimentum nulla. Quisque ultricies accumsan fermentum. Fusce aliquam nunc at urna varius tempor. In molestie sollicitudin sem, id pulvinar orci gravida id. Cras suscipit ornare volutpat.
Nullam luctus molestie lacus posuere eleifend. Cras consectetur tincidunt viverra. Ut nec elit nec est facilisis mattis. Integer tristique consequat gravida. Nulla sit amet tincidunt odio. Proin in massa orci. Suspendisse mattis non nunc vel facilisis.
Pellentesque pretium feugiat placerat. Sed non mauris sed ligula semper vulputate sit amet vehicula nibh. Maecenas accumsan lorem vitae mi pharetra congue. Nulla purus enim, lacinia sed convallis nec, iaculis eu arcu. Vivamus nisl mauris, sollicitudin at magna a, sagittis suscipit eros. In hac habitasse platea dictumst. Aliquam gravida orci augue, quis venenatis risus volutpat vitae. Duis vel augue dignissim, viverra ante at, rutrum mi. Nullam venenatis posuere nisi at malesuada.
Nunc eu quam posuere nisi auctor lobortis. Vestibulum vestibulum est vel purus faucibus, quis tristique velit sagittis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In sodales dui eu iaculis placerat. Nulla semper sem quis nibh dapibus, consectetur ullamcorper urna posuere. Aenean faucibus tincidunt ligula, et consectetur risus rutrum in. Nunc vel scelerisque velit, laoreet posuere orci. Sed tempus auctor quam a pulvinar. Donec felis nibh, auctor ut mattis et, bibendum eget eros. Curabitur eleifend quam vel ex consequat bibendum. Pellentesque et libero sit amet erat dignissim posuere."

file="$TESTSDIR/test1.txt"
# Create the test files
for i in `seq 1 8`
do
    # If file not present, create the test  
    if [ ! -f "$TESTSDIR/test$i.txt" ]; 
    then
        touch "$TESTSDIR/test$i.txt"

        max=5
        if [ $i -eq 4 ]; 
        then
            max=4
        fi
        # if i greater than 5 then max is 2
        if [ $i -gt 5 ]; 
        then
            max=2
        fi
        if [ ! $i -eq 1 ]; 
        then
            # Copy the previous file to the current file 2 times to increase the file size
            for j in `seq 1 $max`
            do
                cat "$TESTSDIR/test$(($i-1)).txt" >> "$TESTSDIR/test$i.txt"
            done
        else
            # Write the lorem ipsum text to the file i x 1000 times
            for j in `seq 1 $((i*80))`
            do
                echo "$LoremIpsum" >> "$TESTSDIR/test$i.txt"
            done
        fi
        echo "test$i.txt created"
    fi
done